// Data structures specific to the Ludo game

export type LudoColor = 'red' | 'green' | 'yellow' | 'blue';

export type LudoPieceState =
  | 'home_yard'      // Piece is in the starting yard, not yet on track
  | 'on_track'       // Piece is on the main game track
  | 'safe_home_run'  // Piece is on its colored home run path
  | 'finished';      // Piece has reached the center/home

export interface LudoPiece {
  pieceId: string; // e.g., "red_1", "blue_3"
  color: LudoColor;
  position: number;
  // Position mapping:
  // -1 to -4: In home yard (specific to piece if needed, or just one "home yard" position like -1)
  // 0-51: Standard track positions (e.g., 0 is start for red, 13 for green, etc. - needs a defined mapping)
  // 101-105: Red home run (106 is home)
  // 201-205: Green home run (206 is home)
  // 301-305: Yellow home run (306 is home)
  // 401-405: Blue home run (406 is home)
  // 999: Finished/Reached center
  state: LudoPieceState;
}

export interface LudoPlayer {
  userId: string; // Links to the platform's user ID
  displayName?: string; // For display
  color: LudoColor;
  pieces: LudoPiece[];
  // Game-specific state for the player during a Ludo match
  hasRolledSixRecently: boolean; // True if the last roll that allowed a move was a six (relevant for getting piece out or another turn)
  consecutiveSixes: number;    // Count of consecutive sixes rolled by this player in their current turn sequence
  // allPiecesFinished?: boolean; // Calculated property
}

export type LudoGamePhase =
  | 'waiting_for_players' // Before game starts
  | 'dice_to_roll'        // Current player needs to roll the dice
  | 'piece_to_move'       // Current player has rolled and needs to select a piece to move
  | 'turn_ended'          // Turn processing complete, moving to next player or checking win
  | 'finished';           // Game has a winner

export interface LudoGameState {
  roomId: string; // Identifier for this specific game instance/room
  gameId: string; // Should be the static ID for "Ludo" from the 'games' metadata table

  players: LudoPlayer[]; // Array of players in the game, usually 2 to 4

  currentPlayerUserId: string | null; // Whose turn is it?
  currentDiceRoll?: number;           // Result of the last dice roll (1-6)

  // Detailed game phase to manage turn flow
  gamePhase: LudoGamePhase;

  // Board state can be implicitly defined by all piece positions,
  // or could have an explicit representation if needed for complex validation/rendering.
  // For now, piece positions define the board state.

  winnerUserId?: string; // Set when a player wins

  turnLog: string[]; // A log of significant actions in the current turn or recent turns
                     // e.g., ["PlayerRed rolled 6", "PlayerRed moved piece R1 from H to S12", "PlayerRed rolls again"]

  // Timestamps for game lifecycle
  createdAt: Date | string;
  startedAt?: Date | string;
  lastMoveAt?: Date | string;
  finishedAt?: Date | string;

  // Configuration for this specific Ludo game instance (could be derived from game metadata)
  // e.g. number_of_pieces_per_player: 4
}

// --- Conceptual API Request/Response types for Ludo actions ---

export interface LudoRollDiceRequest {
  roomId: string;
  userId: string; // User making the request (current player)
}
export interface LudoRollDiceResponse {
  newState: LudoGameState; // The updated game state after the roll
  diceRoll: number;
  actionsPossible: boolean; // Can any piece be moved with this roll?
}

export interface LudoMovePieceRequest {
  roomId: string;
  userId: string; // User making the request (current player)
  pieceId: string;
  // 'steps' might be implicit from currentDiceRoll, or explicit if multiple options
  // For simplicity, let's assume the backend uses currentDiceRoll from state.
  // If a specific number of steps is chosen from multiple options (e.g. after a 6), it could be here.
  // stepsToMove?: number;
}
export interface LudoMovePieceResponse {
  newState: LudoGameState; // The updated game state after the move
  moveSuccessful: boolean;
  message?: string; // e.g., "Piece captured!", "Piece reached home!"
}

export interface CreateLudoGameRequest {
    roomId: string; // Can be provided or generated by Matchmaking
    userIds: string[]; // List of user IDs participating
    // Potentially Ludo-specific settings if they vary per game instance
}
// Response for creating/starting a game would be the initial LudoGameState
