import { Injectable } from '@angular/core';
// import { HttpClient, HttpParams } from '@angular/common/http'; // Conceptual
import { Observable, of } from 'rxjs';
import { delay, map } from 'rxjs/operators';

// Mirroring Leaderboard types from backend conceptual service
export interface LeaderboardEntry {
  userId: string;
  rank: number;
  score: number;
  gamesPlayed: number;
  wins?: number;
  totalWinnings?: number;
  lastPlayedAt?: Date | string;
  displayName?: string;
}

export type Timeframe = 'daily' | 'weekly' | 'monthly' | 'allTime';

export interface Leaderboard {
  leaderboardId: string;
  gameId: string;
  gameName?: string;
  timeframe: Timeframe;
  entries: LeaderboardEntry[];
  generatedAt: Date | string;
}

// Mock data - this would be generated by the backend LeaderboardService
// based on game results. For now, we provide a snapshot.
const MOCK_LEADERBOARDS = new Map<string, Leaderboard>();

const now = new Date().toISOString();
MOCK_LEADERBOARDS.set('ludo_masters_game_id_allTime', {
  leaderboardId: 'lb_ludo_allTime_123', gameId: 'ludo_masters_game_id', gameName: 'Ludo Masters', timeframe: 'allTime', generatedAt: now,
  entries: [
    { userId: 'userA', displayName: 'UserA_LudoChamp', rank: 1, score: 290, gamesPlayed: 3, wins: 2, totalWinnings: 105, lastPlayedAt: new Date(Date.now() - 100000).toISOString() },
    { userId: 'userB', displayName: 'UserB_Pro', rank: 2, score: 210, gamesPlayed: 2, wins: 1, totalWinnings: 60, lastPlayedAt: new Date(Date.now() - 200000).toISOString() },
    { userId: 'userC', displayName: 'UserC_Rook', rank: 3, score: 150, gamesPlayed: 1, wins: 1, totalWinnings: 75, lastPlayedAt: new Date(Date.now() - 300000).toISOString() },
  ]
});
MOCK_LEADERBOARDS.set('ludo_masters_game_id_weekly', {
  leaderboardId: 'lb_ludo_weekly_123', gameId: 'ludo_masters_game_id', gameName: 'Ludo Masters', timeframe: 'weekly', generatedAt: now,
  entries: [ // Assume less data for weekly
    { userId: 'userB', displayName: 'UserB_Pro', rank: 1, score: 120, gamesPlayed: 1, wins: 1, totalWinnings: 60, lastPlayedAt: new Date(Date.now() - 100000).toISOString() },
    { userId: 'userA', displayName: 'UserA_LudoChamp', rank: 2, score: 100, gamesPlayed: 1, wins: 1, totalWinnings: 50, lastPlayedAt: new Date(Date.now() - 150000).toISOString() },
  ]
});
MOCK_LEADERBOARDS.set('rummy_royale_game_id_allTime', {
  leaderboardId: 'lb_rummy_allTime_456', gameId: 'rummy_royale_game_id', gameName: 'Rummy Royale', timeframe: 'allTime', generatedAt: now,
  entries: [
    { userId: 'userB', displayName: 'UserB_RummyKing', rank: 1, score: 420, gamesPlayed: 2, wins: 2, totalWinnings: 210, lastPlayedAt: new Date(Date.now() - 50000).toISOString() },
    { userId: 'userC', displayName: 'UserC_CardSharp', rank: 2, score: 180, gamesPlayed: 1, wins: 0, totalWinnings: 0, lastPlayedAt: new Date(Date.now() - 250000).toISOString() },
  ]
});


@Injectable({
  providedIn: 'root'
})
export class LeaderboardService {
  // private apiUrl = '/api/v1/leaderboards'; // Conceptual

  constructor(/*private http: HttpClient*/) {}

  getLeaderboard(gameId: string, timeframe: Timeframe, limit: number = 100): Observable<Leaderboard | undefined> {
    console.log(`[LeaderboardService] Fetching leaderboard for game ${gameId}, timeframe ${timeframe}, limit ${limit} (mocked)`);
    // const params = new HttpParams().set('timeframe', timeframe).set('limit', limit.toString());
    // return this.http.get<Leaderboard>(`${this.apiUrl}/${gameId}`, { params });

    const key = `${gameId}_${timeframe}`;
    const leaderboard = MOCK_LEADERBOARDS.get(key);

    if (leaderboard) {
      // Simulate limit
      const limitedLeaderboard = { ...leaderboard, entries: leaderboard.entries.slice(0, limit) };
      return of(limitedLeaderboard).pipe(delay(450));
    }
    // Return an empty leaderboard structure if no specific mock found for that combo
    return of({
        leaderboardId: `lb_${gameId}_${timeframe}_empty`, gameId,
        gameName: gameId.replace(/_id$/, '').replace(/_/g, ' '), // simple name generation
        timeframe, entries: [], generatedAt: new Date().toISOString()
    }).pipe(delay(450));
  }
}
