-- Database schema for Analytics-Service (initial raw event storage)
-- This table is designed for collecting raw event data.
-- For complex analytics, this data would typically be ETL'd into a data warehouse (e.g., Redshift, BigQuery).

CREATE TABLE raw_events (
    -- Using UUID for event_id is generally good for distributed systems,
    -- but SERIAL/BIGSERIAL is simpler for basic PostgreSQL setup.
    -- Let's use UUID and assume it's generated by the service upon ingestion if not provided by client.
    event_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), -- Requires pgcrypto extension or similar for gen_random_uuid()
                                                       -- Or use VARCHAR(255) if client generates UUIDs.
                                                       -- For simplicity of this schema without extension needs, we can use VARCHAR(255)
    -- event_pk SERIAL PRIMARY KEY, -- Simpler alternative if not using UUIDs from client

    event_name VARCHAR(255) NOT NULL,
    user_id VARCHAR(255),             -- Nullable, as some events might be anonymous or system events
    session_id VARCHAR(255),          -- Nullable

    event_timestamp TIMESTAMP WITH TIME ZONE NOT NULL, -- Timestamp from the client/source system
    received_timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP, -- When the ingestion service received it

    event_properties JSONB,           -- Stores custom event data. JSONB is preferred in PostgreSQL for indexing and querying.
                                      -- Use TEXT if JSONB is not available, but querying JSON content becomes harder.

    -- Optional common fields that might be extracted or added at ingestion pipeline
    -- client_ip VARCHAR(45),
    -- user_agent TEXT,
    -- app_version VARCHAR(50),
    -- platform VARCHAR(20) -- 'web', 'android', 'ios'
);

-- Indexes for common query patterns on raw_events
CREATE INDEX idx_raw_events_event_name ON raw_events(event_name);
CREATE INDEX idx_raw_events_user_id ON raw_events(user_id);
CREATE INDEX idx_raw_events_event_timestamp ON raw_events(event_timestamp);
CREATE INDEX idx_raw_events_received_timestamp ON raw_events(received_timestamp);

-- For querying JSONB properties (PostgreSQL specific example)
-- CREATE INDEX idx_raw_events_properties_gin ON raw_events USING GIN (event_properties);
-- This allows efficient querying inside the JSONB structure, e.g., WHERE event_properties->>'gameId' = 'ludo123'
